name: CI Enneade

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake g++ openjdk-17-jdk

      - name: Configure project with Ninja Multi-Config
        run: |
           cmake -S . -B build -G "Ninja Multi-Config" \
            -DCMAKE_CXX_STANDARD=14 \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_CONFIGURATION_TYPES="Debug;Release;RelWithDebInfo" \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install \
            -DMPI=OFF \
            -DBUILD_JARS=ON \
            -DTESTING=OFF

      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Run tests
        run: |
          # Find the test executable (Release, Debug, wherever it was built)
          test_exe=$(find build -type f -name 'enneade_test' -executable)
      
          if [[ -z "$test_exe" ]]; then
            echo "❌ Test executable not found!"
            exit 1
          fi
      
          echo "✅ Found test executable at: $test_exe"
          echo "🏃 Running tests..."
      
          # Run the test binary with verbose output
          "$test_exe" --gtest_color=yes --gtest_output=standard
