name: CI Enneade

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build cmake g++ openjdk-17-jdk

      - name: Configure project with Ninja Multi-Config
        run: |
           cmake -S . -B build -G "Ninja Multi-Config" \
            -DCMAKE_CXX_STANDARD=14 \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_CONFIGURATION_TYPES="Debug;Release;RelWithDebInfo" \
            -DCMAKE_INSTALL_PREFIX=${{ github.workspace }}/install \
            -DMPI=OFF \
            -DBUILD_JARS=ON \
            -DTESTING=ON
            
      - name: Build (Release)
        run: cmake --build build --config Release

      - name: Run tests
        run: ctest --test-dir build --build-config Release --output-on-failure
